name: 'Deploy to Int'

on:
  push:
    branches:
      - 'main'

jobs:
  build-push-deploy:
    name: 'Build and Deploy to Integration'
    runs-on: ubuntu-latest

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # gcloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SKYVIEWER_INT_SERVICE_ACCOUNT }}
        project_id: edc-int-6c5e
        export_default_credentials: true

    - name: Build Container Image
      run: |-
        docker build \
        -t "gcr.io/edc-int-6c5e/investigations-client:${{ github.sha }}" \
        --build-arg NEXT_PUBLIC_API_URL=https://investigations-api-dot-edc-int-6c5e.uc.r.appspot.com/api \
        --build-arg NEXT_PUBLIC_BASE_URL=https://investigations-client-dot-edc-int-6c5e.uc.r.appspot.com \
        --build-arg NEXT_PUBLIC_GOOGLE_APP_ID=688095955960-t0fpaj4ec3gh5vsr9lhg8govapk2oeo9.apps.googleusercontent.com \
        --build-arg CRAFT_REVALIDATE_SECRET_TOKEN=1128f3c472c118caa63 \
        --build-arg CRAFT_EDUCATOR_SCHEMA_SECRET_TOKEN=pwx_fhZ19PvKaUelac8tnIGzRjv_87Yf \
        --build-arg CRAFT_STUDENT_SCHEMA_SECRET_TOKEN=5Iqugg1mUGWd8RIC_UfoSbFvry5W2wOk \
        .
    - name: Configure Docker Auth
      run: gcloud --quiet auth configure-docker

    - name: Push Container Image to GCR
      run: docker push gcr.io/edc-int-6c5e/investigations-client:${{ github.sha }}

    - name: Get app.yaml
      run: gcloud secrets versions access latest --secret=investigations-client-appyaml > app.yaml

    - name: Deploy to App Engine
      run: |-
        gcloud app deploy app.yaml \
        --quiet \
        --image-url=gcr.io/edc-int-6c5e/investigations-client:${{ github.sha }} \
        --promote \
        --project=edc-int-6c5e
